# Generated by Django 2.2.3 on 2019-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortnurl',
            name='short_code',
            field=models.CharField(default='start123', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
