# Generated by Django 2.2.3 on 2019-07-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190724_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnurl',
            name='short_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
