# Generated by Django 2.2.3 on 2019-07-25 09:51

from django.db import migrations, models
import shortener.validator


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_shortnurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortnurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validator.clean_url]),
        ),
    ]
